# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim

# set workdir
WORKDIR /app

# install system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      build-essential \
      libglib2.0-0 \
      libgl1-mesa-glx && \
    rm -rf /var/lib/apt/lists/*

# copy project files
COPY pyproject.toml requirements.txt ./
COPY . .

# install python dependencies
RUN pip install --no-cache-dir -U pip && \
    pip install --no-cache-dir .

# expose no ports, uses stdio
CMD ["python", "-m", "src.server"]
